<?php

namespace Database\Seeders;

use App\Models\TempResidentModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PendudukTemporarySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        TempResidentModel::create([
            'id_penduduk' => 6,
            'tgl_lahir' => '1990-01-01',
            'nik' => '1234567890',
            'nomor_kk' => '0987654321',
            'nama' => 'John Doe 1',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Laki-laki',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'jumlah_tanggungan' => 2,
            'status' => 'Menunggu Verifikasi',
        ]);
        TempResidentModel::create([
            'id_penduduk' => 7,
            'tgl_lahir' => '1990-01-01',
            'nik' => '1234567894',
            'nomor_kk' => '0987654324',
            'nama' => 'John Doe 2',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Laki-laki',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'jumlah_tanggungan' => 2,
            'status' => 'Menunggu Verifikasi',
        ]);
        TempResidentModel::create([
            'id_penduduk' => 8,
            'tgl_lahir' => '1990-01-01',
            'nik' => '1234567895',
            'nomor_kk' => '0987654325',
            'nama' => 'John Doe 3',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Laki-laki',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'status' => 'Ditolak',
            'jumlah_tanggungan' => 2,
            'keterangan_status'=> 'Data kurang lengkap!'
        ]);
        TempResidentModel::create([
            'id_penduduk' => 9,
            'tgl_lahir' => '1990-01-01',
            'nik' => '1234567896',
            'nomor_kk' => '0987654326',
            'nama' => 'Loly',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Perempuan',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'jumlah_tanggungan' => 2,
            'status' => 'Diterima',
        ]);
    }
}
