<?php

namespace Database\Seeders;

use App\Models\TempResidentModel;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PendudukTemporarySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        TempResidentModel::create([
            'id_penduduk' => 21,
            'tgl_lahir' => '1990-01-01',
            'nik' => '3579011402040021',
            'nomor_kk' => '3507010201082556',
            'nama' => 'John Doe ',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Laki-laki',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'jumlah_tanggungan' => 2,
            'status' => 'Menunggu Verifikasi',
        ]);
        TempResidentModel::create([
            'id_penduduk' => 22,
            'tgl_lahir' => '1990-01-01',
            'nik' => '3579011402040022',
            'nomor_kk' => '3507010201082556',
            'nama' => 'Istri John Doe ',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Laki-laki',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'jumlah_tanggungan' => 2,
            'status' => 'Menunggu Verifikasi',
        ]);
        TempResidentModel::create([
            'id_penduduk' => 23,
            'tgl_lahir' => '1990-01-01',
            'nik' => '3579011402040023',
            'nomor_kk' => '3507010201082556',
            'nama' => 'Anak John Doe 1',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Laki-laki',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'status' => 'Ditolak',
            'jumlah_tanggungan' => 2,
            'keterangan_status'=> 'Data kurang lengkap!'
        ]);
        TempResidentModel::create([
            'id_penduduk' => 24,
            'tgl_lahir' => '1990-01-01',
            'nik' => '3579011402040024',
            'nomor_kk' => '3507010201082556',
            'nama' => 'Loly Anak John Doe',
            'tempat_lahir' => 'Jakarta',
            'jenis_kelamin' => 'Perempuan',
            'rt' => 001,
            'status_kawin' => 'Belum Menikah',
            'status_keluarga' => 'Kepala Keluarga',
            'agama' => 'Islam',
            'alamat' => 'Jl. Contoh No. 123',
            'pendidikan' => 'Sarjana',
            'pekerjaan' => 'PNS',
            'gaji' => 5000000,
            'pajak_bumi' => 100000,
            'biaya_listrik' => 200000,
            'biaya_air' => 150000,
            'total_pajak_kendaraan' => 2,
            'akseptor_kb' => true,
            'jenis_akseptor' => 'IUD',
            'aktif_posyandu' => true,
            'has_BKB' => true,
            'has_tabungan' => false,
            'ikut_kel_belajar' => true,
            'jenis_kel_belajar' => 'Kursus Komputer',
            'ikut_paud' => false,
            'ikut_koperasi' => true,
            'jumlah_tanggungan' => 2,
            'status' => 'Menunggu Verifikasi',
        ]);
    }
}
